version: '2'

services:

  server:
    image: tzrlk/image-graph:latest
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      PORT: 3000
    ports:
      - 3000:3000/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

